name: climaax_heatwaves

channels:
    - conda-forge

dependencies:
    - python=3.11
    - rasterio
    - pathlib
    - rioxarray
    - cdsapi
    - numpy
    - pandas
    - xarray
    - xarray-spatial
    - cartopy
    - matplotlib
    - gdal
    - jupyterlab
    - geopandas
    - pyproj
    - cfgrib
    - scipy
    - scikit-learn
    - ipyleaflet
    - ipywidgets
    - leafmap
    - localtileserver
    - requests
    - rasterstats
    - plotly
    - folium
    - branca
    - pip

    - pip:
        - netcdf4
        - damagescanner
        - jupyterlab_myst
          
