name: climaax_heatwaves

channels:
    - conda-forge

dependencies:
        - python=3.11
        - rasterio
        - pathlib
        - rioxarray
        - cdsapi
        - numpy
        - pandas
        - xarray
        - xarray-spatial
        - cartopy
        - matplotlib
        - rasterio
        - gdal
        - jupyterlab
        - geopandas
        - pyproj
        - cfgrib
        - scipy
        - pip

        - pip:
            - netcdf4
            - damagescanner
            - jupyterlab_myst
   
          
