name: climaax_heatwaves

channels:
    - conda-forge

dependencies:
    - cartopy=0.23.0
    - cdsapi=0.7.5
    - dask=2024.7.0
    - flask=2.3.3
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - ipyleaflet=0.19.1
    - ipython=8.27.0
    - ipywidgets=8.1.3
    - jupyter-server-proxy=4.4.0
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.7
    - localtileserver=0.10.6
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.2
    - numpy=1.26.4
    - pandas=2.2.2
    - pip
    - plotly=5.22.0
    - python=3.12
    - rasterio=1.3.10
    - rasterstats=0.19.0
    - rio-tiler=7.6.0
    - rioxarray=0.15.7
    - werkzeug=3.1.3
    - xarray=2024.6.0
    - xclim=0.50.0
