name: climaax_heatwaves

channels:
    - conda-forge

dependencies:
        - python=3.11
        - zipfile
        - os
        - rasterio
        - pathlib
        - rioxarray
        - cdsapi
        - numpy
        - pandas
        - xarray
        - osgeo
        - cartopy
        - matplotlib
        - rasterio
        -  glob
        - geopandas
        - pyproj
        - cfgrib
        - scipy

        - pip:
            - netcdf4
            - damagescanner
            - jupyterlab_myst
   
          
